#!/bin/bash

# @file
# Contains the rv command.

# Switches to a specific version of Ruby using RVM.
# If that version isn't installed, it installs it and rails.
function rv {
  echo
  # Gotta give me a version
  if [ -z "${1}" ]; then
    bad_msg "Gotta give me a version!"
    return 1
  fi

  # Gotta have rvm for this.
  if [ -z $(which rvm) ]; then
    bad_msg "No rvm installed. Not touching ruby."
    return 1
  fi

  # See if the version is already available.
  rvm use ruby-${1}

  # If it isn't, attempt to install it and Rails.
  if [ ${?} != 0 ]; then
    yn=$(confirm_msg "Ruby v${1} is not installed. Install it?")
    if [[ "${yn}" =~ (y|Y|[yY]es) ]]; then
      good_msg "Attempting to install Ruby v${1}"
      rvm install ruby-${1}
      rvm use ruby-${1}
      if [ ${?} != 0 ]; then
        bad_msg "Could not install Ruby v${1}"
      else
        good_msg "Installing Rails on Ruby v${1}"
        gem install rails --no-ri --no-rdoc
        good_msg "Ruby v${1} and Rails installed!"
      fi
    fi
  fi
}

