#!/bin/bash

# @file
# Contains aliases to go to various servers

function mira {
  case "${1}" in
    'dev')
      ssh tdrmira-dev-01.uit.tufts.edu
      ;;
    *)
      ssh tdrmira-prod-01.uit.tufts.edu
      ;;
  esac
}

function tdl {
   case "${1}" in
     'dev')
       ssh tdl-dev-01.uit.tufts.edu
       ;;
     *)
       ssh tdl-prod-01.uit.tufts.edu
       ;;
   esac
}

function trove  {
  case "${1}" in
    'dev')
      ssh tdil-dev-02.lib.tufts.edu
      ;;
    *)
      ssh tdil-prod-02.lib.tufts.edu
      ;;
  esac
}

function nnv {
  case "${1}" in
    'dev')
      ssh elections-dev-01.lib.tufts.edu
      ;;
    *)
      ssh elections-prod-01.lib.tufts.edu
      ;;
  esac
}

function dark {
  case "${1}" in
    'dev')
      ssh tdrdark-dev-01.uit.tufts.edu
      ;;
    *)
      ssh tdrdark-prod-01.uit.tufts.edu
      ;;
  esac
}

function streets {
  ssh tdlbst-prod-01.lib.tufts.edu
}

function fed {
  case "${1}" in
    'dev')
      ssh tdrfedora-dev-01.uit.tufts.edu
      ;;
    *)
      ssh tdrfedora-prod-01.uit.tufts.edu
      ;;
  esac
}

function solr {
  case "${1}" in
    'dev')
      ssh tdrsearch-dev-01.uit.tufts.edu
      ;;
    *)
      ssh tdrsearch-prod-01.uit.tufts.edu
      ;;
  esac
}

function spot {
  case "${1}" in
    'dev')
      ssh spotlightweb-dev-01.uit.tufts.edu 
      ;;
    *)
      ssh spotlightweb-prod-01.uit.tufts.edu 
  esac
}

function spot8 {
  case "${1}" in
    'dev')
      ssh spotlight-dev-01.it.tufts.edu
      ;;
    *)
      ssh spotlight-prod-01.it.tufts.edu
  esac
}
